#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('KIT_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap ScrapyardIO and handle the command...
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
