#!/usr/bin/env php
<?php

define('SCRAPYARD_IO_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Boostrap ScrapyardIO and handle the command...
$app = require_once __DIR__.'/bootstrap/app.php';
